name: Actions 😎

on:
  pull_request: {}
  push: { branches: [main] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v2.1.3
        with:
          path: Library
          key: Library

      # Test
      - name: Run tests
        id: myTestStep
        uses: webbertakken/unity-test-runner@v1.7
        with:
          customParameters: '-nographics' # <--- Remove when test runner is working for Unity 2020
          unityVersion: 2020.1.10f1
      # Test Results
      - name: Upload test results
        uses: actions/upload-artifact@v1
        with:
            name: Test results
            path: artifacts
      # Build
      - name: Build project
        uses: webbertakken/unity-builder@v1.5
        with:
          unityVersion: 2020.1.10f1
          targetPlatform: WebGL
          versioning: None  # <--- Change to semantic versioning later

      # Output
      - name: Upload build
        uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
      # Deploy to local repo
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.PA_TOKEN }}